#this is scriptative jenkins file

node{
    agent any
    stages{
        stage('git checkout') {
        steps{
            sh 'git clone url'
        }
        }
        stage('unit testing'){
            steps{
                sh 'mvn test'
            }
        }
        stage('maven package'){
            steps{
                sh 'mvn clean package'
            }
        }
        stage('sonar checks'){
            steps{
                sh 'code generated by pipeline syntax in jenkins'
                sh 'mvn sonar:sonar'
            }
        }
        stage('sonar QA'){
            steps{
                sh 'code generated by pipeline syntax in jenkins with quality gate plugin'
            }
        }
        stage('artifact to nexus repo'){
            steps{
                sh 'code generated by pipeline syntax in jenkins'
            }
        }
        stage('tomcat deploy'){
            steps{
                sh 'mvn clean deploy'
            }
        }
    }
}